- name: Deploy Log Viewer to a single node using Docker
  hosts: node1
  become: yes
  vars:
    app_dir: /opt/log_viewer
    image_name: log_viewer
    container_name: log_viewer
    port: 27015
    repo_url: https://github.com/psych0panda/log_viewer.git

  tasks:
    - name: Install prerequisites
      apt:
        name:
          - docker.io
          - python3-docker
          - git
        state: present
        update_cache: yes

    - name: Ensure Docker service is running and enabled
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Clone or update the repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: master
        force: yes

    - name: Build Docker image from Dockerfile
      community.docker.docker_image:
        name: "{{ image_name }}"
        build:
          path: "{{ app_dir }}"
        source: build
        state: present
      notify: Restart log_viewer container

    - name: Create and run Log Viewer container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        restart_policy: always
        ports:
          - "{{ port }}:{{ port }}"

    - name: Print application URL
      debug:
        msg: "Application is deployed and running at http://{{ inventory_hostname }}:{{ port }}"

  handlers:
    - name: Restart log_viewer container
      community.docker.docker_container:
        name: "{{ container_name }}"
        restart: yes
